name:                maf2-analysis
version:             0.1.0.0
github:              "github.com/softwarelanguageslab/maf-hs"
license:             GPL3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2023 Author name here"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/maf2-hs#readme>

dependencies:
- base >= 4.7 && < 5
- QuickCheck >= 2.14.2
- hspec 
- hspec-contrib
- hashable
- HUnit
- containers
- unordered-containers
- data-default
- mtl
- transformers
- lens
- criterion
- language-python
- vector
- optparse-applicative
- IfElse
- maf2-domains
- maf2-syntax
- maf2-typelevel
- hashmap
- list-t

default-extensions:
  - FlexibleContexts
  - TypeFamilies
  - TupleSections
  - TemplateHaskell
  - NamedFieldPuns
  - TypeOperators
  - InstanceSigs
  - DeriveGeneric
  - TypeApplications
  - StandaloneDeriving
  - ScopedTypeVariables
  - DataKinds
  - MultiParamTypeClasses
  - FunctionalDependencies
  - GeneralizedNewtypeDeriving

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints
- -fno-warn-type-defaults
- -O0
- -fprint-potential-instances
- -fprof-auto
- -fprof-cafs

library:
  source-dirs: src
  exposed-modules:
  - Analysis.Scheme.Simple
  - Analysis.Scheme.Semantics
  - Analysis.Scheme.Primitives
  - Analysis.Monad
  - Analysis.Scheme
  - Analysis.Scheme.Monad
  - Analysis.Scheme.Store
  - Interpreter.Scheme
  - Control.SVar.ModX
  - Control.Monad.Layer

executables:
  maf-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - maf2-analysis
    - pretty-simple

tests:
  maf2-analysis-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - maf2-analysis
