resolver:
  url: https://raw.githubusercontent.com/commercialhaskell/stackage-snapshots/master/lts/21/25.yaml

packages:
 - maf2-analysis/
 - maf2-syntax/
 - maf2-domains/
 - maf2-typelevel/
 - maf2-scv/
