name:                maf2-domains
version:             0.1.0.0
github:              "softwarelanguageslab/maf-hs"
license:             BSD3
author:              "Software Languages Lab"
maintainer:          ""
copyright:           "2023 Software Languages Lab"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/maf2-domains#readme>

dependencies:
- base >= 4.7 && < 5
- containers
- unordered-containers
- mtl
- transformers
- data-default
- extra
- maf2-syntax
- hashable
- vector 
- singletons
- singletons-th
- template-haskell

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src
  exposed-modules: 
    - Domain
    - Domain.Class
    - Domain.Core 
    - Domain.Core.HMapDomain 
    - Domain.Core.SeqDomain 
    - Domain.Scheme
    - Domain.Scheme.Class
    - Domain.Scheme.Derived
    - Domain.Scheme.Derived.Pair
    - Domain.Scheme.Store
    - Domain.Scheme.Modular
    - Domain.Python
    - Domain.Python.World
    - Domain.Python.Objects
    - Domain.Python.Syntax
    - Domain.Scheme.Actors.Class
    - Domain.Scheme.Actors
    - Domain.Scheme.Actors.CP
    - Domain.Scheme.Actors.Contract
    - Domain.Erlang.Class
    - Lattice
    - Lattice.Class 
    - Lattice.ConstantPropagationLattice
    - Lattice.ReversePowerSetLattice
    - Control.Monad.Cond
    - Control.Monad.Join
    - Control.Monad.DomainError
    - Control.Monad.AbstractM
    - Control.Monad.Escape
    - Data.TypeLevel.HMap
    - Data.Finite 
    - Domain.Core.SeqDomain.BoundedList

default-extensions:
  - TypeFamilies
  - TupleSections
  - TemplateHaskell
  - NamedFieldPuns
  - TypeOperators
  - InstanceSigs
  - DeriveGeneric
  - TypeApplications
  - StandaloneDeriving
  - ScopedTypeVariables
  - DataKinds
  - MultiParamTypeClasses
  - FunctionalDependencies
  - GeneralizedNewtypeDeriving
  - StandaloneKindSignatures
  - ConstraintKinds
  - FlexibleInstances
  - FlexibleContexts
  - RankNTypes
  - GADTs
  - LambdaCase
  - EmptyCase 


tests:
  maf2-domains-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - maf2-domains
    - QuickCheck >= 2.14.2
    - hspec 
    - hspec-contrib
    - HUnit

