resolver:
  url: https://raw.githubusercontent.com/commercialhaskell/stackage-snapshots/master/lts/21/25.yaml

packages:
- .
extra-deps:
  - github: softwarelanguageslab/maf-hs
    commit: cd936e0558953eaa468c65a373049dd5e0ae245a
    subdirs:
      - maf2-analysis
      - maf2-syntax
      - maf2-domains
  - github: bramvdbogaerde/layers-mtl
    commit: 5201fd1814053630f762c382a79e49b7bf14df8f
